language: go
arch: amd64
os: linux             # required for arch different than amd64
dist: focal           # or bionic | xenial with xenial as default
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - echo "${TRAVIS_BUILD_DIR}"
  - cd /tmp
  - wget https://linuxcontainers.org/downloads/distrobuilder/distrobuilder-1.1.tar.gz --directory-prefix=/tmp/
  - ls
  - tar -xvf /tmp/distrobuilder-1.1.tar.gz
  - cd distrobuilder-1.1
  - sudo apt install snapd
  - sudo snap install distrobuilder --edge --classic
  - mkdir -p ContainerImages/ubuntu/
  - cd ContainerImages/ubuntu/
  - curl -O https://raw.githubusercontent.com/lxc/lxc-ci/master/images/alpine.yaml
  - sudo distrobuilder build-lxc alpine.yaml
