language: go
arch: arm64-graviton2 # in AWS over Graviton2 CPU
virt: lxd             # required, routes to an LXD container
os: linux             # required for arch different than amd64
dist: focal           # or bionic | xenial with xenial as default
group: edge
before_script:
  - wget https://linuxcontainers.org/downloads/distrobuilder/distrobuilder-1.1.tar.gz /tmp/
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - echo "${TRAVIS_BUILD_DIR}"
  - cd /tmp
  - tar -xvf ${TRAVIS_BUILD_DIR}/distrobuilder-1.1.tar.gz
  - cd distrobuilder-1.1
  - ls
