arch: amd64          # optional, this is default, routes to a full VM
os: linux            # optional, this is default
dist: focal          # or bionic | xenial | trusty | precise with xenial as default
language: go
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - echo "${TRAVIS_BUILD_DIR}"
  - cd /tmp
  - wget https://linuxcontainers.org/downloads/distrobuilder/distrobuilder-1.1.tar.gz --directory-prefix=/tmp/
  - ls
  - tar -xvf /tmp/distrobuilder-1.1.tar.gz
  - cd distrobuilder-1.1
  - sudo apt install snapd -y
  - sudo snap install distrobuilder --edge --classic
  - mkdir -p ContainerImages/distro/
  - cd ContainerImages/distro/
  - curl -O https://raw.githubusercontent.com/lxc/lxc-ci/master/images/debian.yaml
  - wget http://archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.123ubuntu2_all.deb
  - sudo dpkg -i debootstrap_1.0.123ubuntu2_all.deb
script:
  - sudo distrobuilder build-lxc debian.yaml -o image.release=sid
  - ls
